### ISSUE TITLE
Cannot open Hibernate Session

### ISSUE THREAD

**Issue by jonnybot0** [limcheekin/activiti#20]
Whenever I run integration tests on my Grails 2.3.6 application that uses the activiti plugin, I receive this error:

```
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is java.lang.IllegalStateException: Already value [org.springframework.jdbc.datasource.ConnectionHolder@43300672] for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy@4c71ec3a] bound to thread [main]; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is java.lang.IllegalStateException: Already value [org.springframework.jdbc.datasource.ConnectionHolder@43300672] for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy@4c71ec3a] bound to thread [main]
    at grails.test.mixin.integration.IntegrationTestMixin.initIntegrationTest(IntegrationTestMixin.groovy:58)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.spockframework.runtime.extension.builtin.JUnitFixtureMethodsExtension$FixtureType$FixtureMethodInterceptor.intercept(JUnitFixtureMethodsExtension.java:145)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:84)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is java.lang.IllegalStateException: Already value [org.springframework.jdbc.datasource.ConnectionHolder@43300672] for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy@4c71ec3a] bound to thread [main]
    ... 7 more
Caused by: java.lang.IllegalStateException: Already value [org.springframework.jdbc.datasource.ConnectionHolder@43300672] for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy@4c71ec3a] bound to thread [main]
    ... 7 more
```

This error occurs as soon as the integration test phase starts, before any particular test is run.

I've also tried this with the version 5.15 fork that arief-hidayat spun up https://github.com/arief-hidayat/activiti/tree/v5.15. Same error. 

I'm running a Grails app on an Oracle database, and my Activiti engine is installed there as well, in a schema specified in my configuration.

Thoughts?

**Comment by limcheekin** [comment]
Thanks for report the issue. Unfortunately I couldn't find time to look into it

**Comment by bwilson** [comment]
I have this error with the 5.15.1 fork at https://github.com/morphace/activiti. Has anybody found a solution?

**Comment by bwilson** [comment]
Jonny, do you have multiple datasources defined? I created a new test app with Activiti 5.15.1 and Grails 2.4.3 and only get this error when I define a second datasource.

**Comment by jonnybot0** [comment]
I do have multiple data sources defined. That could be the issue.

**Comment by dustindclark** [comment]
@jonnybot0 @bwilson , I know this is old, but did you ever resolve this issue?  If so, how?  Thanks in advance.
