### ISSUE TITLE
task.id is null (NullPointerException) in Grails 2.0.3 and Activiti 5.8.2

### ISSUE THREAD

**Issue by limcheekin** [limcheekin/activiti#5]
When click on "start" link of Vacation Request after login as kermit, throws
java.lang.NullPointerException: Cannot get property 'id' on null object
    at ActivitiGrailsPlugin$_addActivitiMethods_closure7_closure29.doCall(ActivitiGrailsPlugin.groovy:129)
    at ActivitiGrailsPlugin$_addActivitiMethods_closure7.doCall(ActivitiGrailsPlugin.groovy:125)
    at vacationRequest.VacationRequestController$_closure2.doCall(VacationRequestController.groovy:36)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)

**Comment by limcheekin** [comment]
Not happened in Grails 2.1.0

**Comment by oswaldl** [comment]
well ,i am using grails 2.2.4, it happens.

**Comment by oswaldl** [comment]
problem solved by empty assignee of the task i designed.
